FROM mysql

RUN echo "default-authentication-plugin=mysql_native_password" >> /etc/my.cnf
COPY ./config/mysql/config-custom.cnf /etc/my.cnf

COPY ./config/mysql/mysql-init.sh /docker-entrypoint-initdb.d/mysql-custom.sh

RUN chmod +x /docker-entrypoint-initdb.d/mysql-custom.sh

RUN chown -R mysql:mysql /var/lib/mysql